sudo: false

git:
  submodules: false

language: php
php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2

env:
  - JVERSION_TEST=staging

matrix:
  fast_finish: true
  allow_failures:
    - php: 8.0

branches:
  only:
    - development
    - feature/fof4
    - debug-travis

before_install:
  - git clone -b "$JVERSION_TEST" https://github.com/joomla/joomla-cms.git Tests/environments/"$JVERSION_TEST"

install:
  - composer selfupdate
  - composer install

before_script:
  - mysql -u root -e 'create database fof_test;'
  - mysql -u root -e "CREATE USER 'fof_db'@'localhost' IDENTIFIED BY 'fof';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON fof_test.* TO 'fof_db'@'%' IDENTIFIED BY 'fof';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON fof_test.* TO 'fof_db'@'localhost' IDENTIFIED BY 'fof';"
  - mysql -u root -e 'FLUSH PRIVILEGES;'

after_script:
  - cat Tests/debug.txt

notifications:
  email: false
