<?php
/**
 * @package   FOF
 * @copyright Copyright (c)2010-2021 Nicholas K. Dionysopoulos / Akeeba Ltd
 * @license   GNU General Public License version 2, or later
 */


class ControllerFactoryDataprovider
{
	public static function getTestMake()
	{
		$data[] = [
			[
				'name'         => '',
				'config'       => [],
				'component'    => 'com_fakeapp',
				'backend_path' => JPATH_TESTS . '/Stubs/Fakeapp/Admin',
			],
			[
				'case'        => 'Name not provided',
				'exception'   => true,
				'result'      => '',
				'autoRouting' => '',
				'csrf'        => 0,
				'view'        => '',
				'model'       => '',
				'priv'        => [],
				'cache'       => [],
				'taskMap'     => [],
			],
		];

		$data[] = [
			[
				'name'         => 'foobars',
				'config'       => [],
				'component'    => 'com_fakeapp',
				'backend_path' => '',
			],
			[
				'case'        => 'The default datacontroller exists',
				'exception'   => false,
				'result'      => 'Fakeapp\Site\Controller\DefaultDataController',
				'autoRouting' => 1,
				'csrf'        => 2,
				'view'        => 'Foobars',
				'model'       => 'Foobars',
				'priv'        => [
					'*editown'    => 'core.edit.own',
					'add'         => 'core.create',
					'apply'       => '&getACLForApplySave',
					'archive'     => 'core.edit.state',
					'cancel'      => 'core.edit.state',
					'copy'        => '@add',
					'edit'        => 'core.edit',
					'loadhistory' => '@edit',
					'orderup'     => 'core.edit.state',
					'orderdown'   => 'core.edit.state',
					'publish'     => 'core.edit.state',
					'remove'      => 'core.delete',
					'save'        => '&getACLForApplySave',
					'savenew'     => 'core.create',
					'saveorder'   => 'core.edit.state',
					'trash'       => 'core.edit.state',
					'unpublish'   => 'core.edit.state',
					'forceRemove' => 'core.delete',
				],
				'cache'       => ['browse', 'read'],
				'taskMap'     => [
					'browse'             => 'browse',
					'read'               => 'read',
					'add'                => 'add',
					'edit'               => 'edit',
					'apply'              => 'apply',
					'copy'               => 'copy',
					'save'               => 'save',
					'savenew'            => 'savenew',
					'cancel'             => 'cancel',
					'publish'            => 'publish',
					'unpublish'          => 'unpublish',
					'archive'            => 'archive',
					'trash'              => 'trash',
					'checkin'            => 'checkin',
					'saveorder'          => 'saveorder',
					'orderdown'          => 'orderdown',
					'orderup'            => 'orderup',
					'remove'             => 'remove',
					'getIDsFromRequest'  => 'getIDsFromRequest',
					'loadhistory'        => 'loadhistory',
					'getItemidURLSuffix' => 'getItemidURLSuffix',
					'display'            => 'display',
					'main'               => 'main',
					'__default'          => 'main',
					'forceRemove'        => 'forceRemove',
					'save2copy'          => 'save2copy',
				],
			],
		];

		$data[] = [
			[
				'name'         => 'foobars',
				'config'       => [
					'taskMap' => [
						'browse' => 'main',
					],
				],
				'component'    => 'com_dummyapp',
				'backend_path' => '',
			],
			[
				'case'        => 'The default datacontroller does not exist, passing the config',
				'exception'   => false,
				'result'      => 'FOF40\\Controller\\DataController',
				'autoRouting' => 1,
				'csrf'        => 2,
				'view'        => 'Foobars',
				'model'       => 'Foobars',
				'priv'        => [
					'*editown'    => 'core.edit.own',
					'add'         => 'core.create',
					'apply'       => '&getACLForApplySave',
					'archive'     => 'core.edit.state',
					'cancel'      => 'core.edit.state',
					'copy'        => '@add',
					'edit'        => 'core.edit',
					'loadhistory' => '@edit',
					'orderup'     => 'core.edit.state',
					'orderdown'   => 'core.edit.state',
					'publish'     => 'core.edit.state',
					'remove'      => 'core.delete',
					'save'        => '&getACLForApplySave',
					'savenew'     => 'core.create',
					'saveorder'   => 'core.edit.state',
					'trash'       => 'core.edit.state',
					'unpublish'   => 'core.edit.state',
					'forceRemove' => 'core.delete',
				],
				'cache'       => ['browse', 'read'],
				'taskMap'     => [
					'browse'             => 'main',
					'read'               => 'read',
					'add'                => 'add',
					'edit'               => 'edit',
					'apply'              => 'apply',
					'copy'               => 'copy',
					'save'               => 'save',
					'savenew'            => 'savenew',
					'cancel'             => 'cancel',
					'publish'            => 'publish',
					'unpublish'          => 'unpublish',
					'archive'            => 'archive',
					'trash'              => 'trash',
					'checkin'            => 'checkin',
					'saveorder'          => 'saveorder',
					'orderdown'          => 'orderdown',
					'orderup'            => 'orderup',
					'remove'             => 'remove',
					'getIDsFromRequest'  => 'getIDsFromRequest',
					'loadhistory'        => 'loadhistory',
					'getItemidURLSuffix' => 'getItemidURLSuffix',
					'display'            => 'display',
					'main'               => 'main',
					'__default'          => 'main',
					'forceRemove'        => 'forceRemove',
					'save2copy'          => 'save2copy',
				],
			],
		];

		$data[] = [
			[
				'name'         => 'foobars',
				'config'       => [],
				'component'    => 'com_dummyapp',
				'backend_path' => JPATH_TESTS . '/Stubs/Dummyapp/Admin',
			],
			[
				'case'        => 'The default datacontroller does not exist, reading fof xml file',
				'exception'   => false,
				'result'      => 'FOF40\\Controller\\DataController',
				'autoRouting' => 1,
				'csrf'        => 2,
				'view'        => 'Foobars',
				'model'       => 'Foobars',
				'priv'        => [
					'*editown'    => 'core.edit.own',
					'add'         => 'core.create',
					'apply'       => '&getACLForApplySave',
					'archive'     => 'core.edit.state',
					'cancel'      => 'core.edit.state',
					'copy'        => '@add',
					'edit'        => 'core.edit',
					'loadhistory' => '@edit',
					'orderup'     => 'core.edit.state',
					'orderdown'   => 'core.edit.state',
					'publish'     => 'core.edit.state',
					'remove'      => 'core.delete',
					'save'        => '&getACLForApplySave',
					'savenew'     => 'core.create',
					'saveorder'   => 'core.edit.state',
					'trash'       => 'core.edit.state',
					'unpublish'   => 'core.edit.state',
					'forceRemove' => 'core.delete',
				],
				'cache'       => ['browse', 'read'],
				'taskMap'     => [
					'browse'             => 'read',
					'read'               => 'read',
					'add'                => 'add',
					'edit'               => 'edit',
					'apply'              => 'apply',
					'copy'               => 'copy',
					'save'               => 'save',
					'savenew'            => 'savenew',
					'cancel'             => 'cancel',
					'publish'            => 'publish',
					'unpublish'          => 'unpublish',
					'archive'            => 'archive',
					'trash'              => 'trash',
					'checkin'            => 'checkin',
					'saveorder'          => 'saveorder',
					'orderdown'          => 'orderdown',
					'orderup'            => 'orderup',
					'remove'             => 'remove',
					'getIDsFromRequest'  => 'getIDsFromRequest',
					'loadhistory'        => 'loadhistory',
					'getItemidURLSuffix' => 'getItemidURLSuffix',
					'display'            => 'display',
					'main'               => 'main',
					'__default'          => 'main',
					'forceRemove'        => 'forceRemove',
					'save2copy'          => 'save2copy',
				],
			],
		];

		return $data;
	}
}
